remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Food Classifier
description: An image classification API that classifies 303 different types of foods

author:
  name: Tirtha Debnath
